### ISSUE TITLE
Custom notfication depending on version

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo-status#12]
In some cases it would be good to have the ability to restrict notifications to certain versions of c:geo or at least to define a upper limit of the version number for which the notification is shown.

Example:
We currently have a notification regarding the live map issue.
If a user updates from 2016.11.05 (old release version) to 2016.12.28 (release where this is fixed) he will still see the notification once he starts up the new version. That is irritating for the user.
If we could post a notification and define to show it only on version codes <= 2016.11.05 this would solve this problem.

**Comment by Bananeweizen** [comment]
An alternative might be: If a notification message exists and the app detects itself as not current (however that might work), we could enforce updating from within the app. That way, instead of supporting some different notifications depending on how old the version in use is, we could basically declare every non-current version as deprecated.

**Comment by mucek4** [comment]
I wouldn't force as you might be in a really low signal area and you will not be able to use c:geo

**Comment by samueltardieu** [comment]
This is implemented. See the create notification job in the CI. As a test, developer builds should right now receive a test notification, while other builds won't. I would appreciate a confirmation (any developer build should work, as the modifications do only affect the server).

Note that right now we still can only have one active notification at a time. Having several should be another issue if needed.

**Comment by Lineflyer** [comment]
Great @samueltardieu . And thanks for the perfect documentation and examples!
