### ISSUE TITLE
Version name and code no longer shown

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo-status#16]
Currently status.cgeo.org is missing the information about version code and version name:
![2017-03-31 13_18_50-c_geo deployment status](https://cloud.githubusercontent.com/assets/949669/24548268/9eaa9054-1614-11e7-8e96-2e6eb250e7b6.jpg)

**Comment by samueltardieu** [comment]
I'll revert the latest change and investigate later.
