### ISSUE TITLE
Custom notification should get higher prio than default update notification

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo-status#17]
I just posted a custom notification for ```kind == "release" && versionName < "2017.03.19"``` but it seems it is not actively seen by users as the older versions will be `kind == "old release"` and thus receive the default update notification.
It would be more helpful if either the custom notification gets higher priority than others or the custom notification would also support other `kind` values (such as `oldrelease` etc.)

This would allow us to notify the users about special (urgent) needs to update.

**Comment by Lineflyer** [comment]
Addon:

I just tested also the condition `versionName < "2017.03.19" && kind != "legacy"` which does not limit to `kind == "release`. 
Still the old version shows only the default update notification.

**Comment by Lineflyer** [comment]
@samueltardieu If you are still interested and find some time, this priorisation would be helpful to have the ability to inform users e.g. about special urgency to perform an update.

**Comment by samueltardieu** [comment]
I have started working on it in #19.

**Comment by Lineflyer** [comment]
Very cool!

**Comment by samueltardieu** [comment]
@Lineflyer See #19 for the tests I've made. I also updated the description on the CI help for the job.
