### ISSUE TITLE
Add services statistics

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo-status#20]
Is it possible to have also statistics about services usage? Something like
Geocaching.com - 90%
Opencaching - 7%
Extremecaching - 2%
Geocaching.su - 1%

**Comment by samueltardieu** [comment]
If someone were to add this to cgeo (a new "enabled services" parameter for example), we could do this.

**Comment by Lineflyer** [comment]
Side note:
Once this is realized it would be good to see absolute numbers for each connector as well as percentage for each (whereas sum of percentages of all connectors might be >100% due to several connectors active for one user, no need to see the combinations IMHO).

**Comment by Lineflyer** [comment]
Server side has just been merged in https://github.com/cgeo/cgeo/pull/7343

**Comment by okainov** [comment]
@samueltardieu do you have any plans to implement this anyhow soon?

**Comment by samueltardieu** [comment]
I'll try to find some time during next week.

**Comment by samueltardieu** [comment]
Cf. https://github.com/cgeo/cgeo.github.io/issues/188 for the missing part.
