### ISSUE TITLE
End of life of Heroku-16 stack

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo-status#23]
Your Heroku account has one or more apps running on the Heroku-16 stack, which reaches end-of-life on May 1st, 2021.

What do I need to do?
Please upgrade your Heroku-16 apps to a newer stack using our Dev Center Guide.

What will happen to apps that are not upgraded?
From March 15th, 2021: To ensure all users notice the end-of-life warnings, a Heroku-16 app's first deploy of the week will fail; all subsequent deploys are unaffected and your apps will continue to run. The frequency of these periodic alerts will increase as the end-of-life date draws closer, as outlined in the linked changelog article.

From May 1st, 2021: Heroku-16 will have reached end-of-life. Existing Heroku-16 apps will continue to operate, but they will no longer receive security updates and they will run at your own risk.

From June 1st, 2021: The building of Heroku-16 apps will no longer be allowed. All other non-build functionality will continue to work, and the apps will continue to run.

What apps do I have on the Heroku-16 stack? 
Your account ************ has the following personal and/or team apps running on Heroku-16:

cgeo-status

Note: This may be a partial list and will not reflect changes made in the last week. For the definitive list of apps, use the Heroku CLI commands. provided in the Heroku End-Of-Life FAQ.

.

**Comment by samueltardieu** [comment]
I'll take care of it.

**Comment by samueltardieu** [comment]
Done.

**Comment by Lineflyer** [comment]
Wow...that was fast. Thanks a lot!
