### ISSUE TITLE
Percentace on status page shows NaN

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo-status#26]
While nothing has changed on this repo, suddenly the status page shows NaN for the connectors information (user percentage):
![image](https://user-images.githubusercontent.com/949669/125356250-3e84ec00-e366-11eb-86d9-482f21c71deb.png)

**Comment by eddiemuc** [comment]
Obviously something is wrong in the "summing up" of all users (shows NaN too). Then, when calculating the percentage (dividing by NaN), the result is NaN.

Maybe one connector delivering NaN in the background for the sum?

**Comment by samueltardieu** [comment]
@Lineflyer Did you check your javascript console? Was there any error exposed?

**Comment by Lineflyer** [comment]
Sorry, I wasn't that clever to look into the console and right now the problem is gone.
If I ever see it again I will take a look into the console.

**Comment by Lineflyer** [comment]
Today I have seen the problem again. The browser console shows no error.
After some minutes values are showing again.

**Comment by bekuno** [comment]
The problem is persistent.
@samueltardieu Can you check this please?

**Comment by samueltardieu** [comment]
This can be fixed either here or in the HTML, I've submitted https://github.com/cgeo/cgeo.github.io/pull/338 to avoid deploying a new version of the application as I don't have the Heroku credentials anymore.

**Comment by SammysHP** [comment]
Thanks, nice to hear from you!

> as I don't have the Heroku credentials anymore.

That is something we should investigate further. I still have my credentials, but my account got removed due to inactivity in 2022. Who is currently in control of our application?

**Comment by Lineflyer** [comment]
Thats probably me. 
At least I have credentials for logging into administration and payment details.

No idea what to do. I can check whether I can create user accounts, shall I?

**Comment by samueltardieu** [comment]
> That is something we should investigate further. I still have my credentials, but my account got removed due to inactivity in 2022. Who is currently in control of our application?

Hi @SammysHP.

My account on Heroku has been removed for the same reason at the end of 2023. @Lineflyer was in control of the Heroku credentials last time I checked.

**Comment by samueltardieu** [comment]
> No idea what to do. I can check whether I can create user accounts, shall I?

If you want I can recreate an account so that you can grant me the access in case of an emergency, and it would be safer if @SammysHP had access as well.

**Comment by Lineflyer** [comment]
I guess I have to add you both as collaborators then?!
For this I need your mail address (probably related to an existing heroku account?!). Just send it via gc@droescher.eu

**Comment by samueltardieu** [comment]
> I guess I have to add you both as collaborators then?! For this I need your mail address (probably related to an existing heroku account?!). Just send it via (removed)

Sent to your gmail.

**Comment by samueltardieu** [comment]
I realized that I can no longer push into this repository. I've done some maintenance on the cgeo-status application (including fixing the bug described in this issue), and I've pushed the changes on Heroku, but I cannot push them here.

Could you allow me to push here so that I can mirror here what is pushed on Heroku? In the meantime, the up-to-date code can be found in the https://github.com/samueltardieu/cgeo-status fork, and I've opened a PR here also (that you don't need to merge if you restore my access).

**Comment by Lineflyer** [comment]
@samueltardieu 
This is related to the organization access rules, where we shifted you from core member to member.
I enabled write access to this repository for you now.
