### ISSUE TITLE
Version info and statistics about old releases gone

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo-status#28]
See here:

![image](https://user-images.githubusercontent.com/949669/206287553-9a00b6c1-c545-4d7e-b2d1-25f34f95e9eb.png)

@samueltardieu 
Any idea what happend?

**Comment by Lineflyer** [comment]
The problem seems to be, that the release information was lost.
I triggered the notification job via CI for the current release and built a new nightly to trigger an update of the status system.
Strangely the todays nightly build should have triggered that anyway, but seemingly did not succeed.

Now it looks kind of normal:
![image](https://user-images.githubusercontent.com/949669/206407350-0b9d177a-956a-4e27-b079-8ba5d3e5fd48.png)

(Remark: I did not set a version code for the well outdated legacy...I would leave this blank for now).

I will monitor this next days to see whether it happens again and whether next nightly runs will correctly update the version.

**Comment by Lineflyer** [comment]
@samueltardieu 
After a day all version information is lost again on status.cgeo.org. 
This also means there is no notification available in the app (e.g. update info for releases and nightlies).

Can you have a look whats going on?

**Comment by Lineflyer** [comment]
After I logged in on Heroku, which powers the notification system I can see the following:
![image](https://user-images.githubusercontent.com/949669/206856804-70508103-7b05-4461-9678-12272e03080c.png)

and

![image](https://user-images.githubusercontent.com/949669/206856815-c0d8e8cd-0db7-49d3-8ecc-4271773464a7.png)

Could be related...but I have no real clue how this backend works.

**Comment by Lineflyer** [comment]
It seems the underlying postgresSQL database is no longer included in our plan but needs an addon.
We probably need @samueltardieu to take a look of how to add this to our plan and implement it again. Money is not the problem.

**Comment by bekuno** [comment]
A short description how to switch to a paid database is at https://blog.heroku.com/eco-and-mini-plans-ga .
You see the current pricing at https://elements.heroku.com/addons/heroku-postgresql#pricing.
The price ist starting at 5€/month.

**Comment by Lineflyer** [comment]
Thanks @bekuno 
I do however have no idea how to reintegrate a new DB.
I just sent a mail to Samuel. Maybe he can help. Otherwise I will start puzzling after Christmas.

**Comment by samueltardieu** [comment]
Hi @Lineflyer. Have you tried adding the "Heroku Postgres" addon to the Heroku app (you're the only one with the rights to do so – chose the smallest plan, $5/month) and restarting the app?

**Comment by Lineflyer** [comment]
If its so easy I will try next days. Wasn't sure if the app will recreate the tables.

Thanks for guidance. Will report back here.

**Comment by Lineflyer** [comment]
Problem is hopefully fixed. Thanks @samueltardieu and @bekuno for helpful information.

For documentation:
- Added postgress DB addon ($5/month) to our Heroku account
- Restarted dyno
- Pushed notification via CI for the current release
- Run a new nightly build to push a notification for the new nightly build

From now on update info to users should be available again.
Reopen if this is not the case.

MERRY CHRISTMAS once again to all!

**Comment by Lineflyer** [comment]
Edit: Nightly job is currently failing (unrelated to here), therefore version info is not yet shown for nightlies on status.cgeo.org.

**Comment by moving-bits** [comment]
Thanks for fixing the status page.

> Edit: Nightly job is currently failing (unrelated to here), therefore version info is not yet shown for nightlies on status.cgeo.org.

Maybe some adaption in the build script needed for `keys.xml` deletion?

```
[...]
20:43:56  BUILD SUCCESSFUL in 10m 16s
20:43:56  122 actionable tasks: 108 executed, 11 from cache, 3 up-to-date
20:43:59  + rm private.properties
20:43:59  + rm ./main/res/values/keys.xml
20:43:59  rm: cannot remove './main/res/values/keys.xml': No such file or directory
20:43:59  Build step 'Execute shell' marked build as failure
[...]
```

**Comment by Lineflyer** [comment]
@moving-bits 
I commented out this command for now. 
Not sure why the keys.xml is not in this place. The nightly just produced runs fine however (including OC, GMaps, etc. which needs keys).

Did you change the project directory structure already or not yet?

**Comment by moving-bits** [comment]
> Did you change the project directory structure already or not yet?

Yes, project structure is changed already, see #13778, so `keys.xml` is now in `main/src/main/res/values/keys.xml`. Maybe copying the file before the build got adapted, but not removal of the file at the end of the build?

**Comment by Lineflyer** [comment]
Yes, seems like that.
The initial storage of keys.xml is handled inside gradle or whereever.
We clean it up to make sure those private keys do not remain in some artefact archive on the CI.

Will adapt it.

BTW: Why are we now using this doubled ```main``` in the path....did not follow all the many posts/mails on that topic.

**Comment by Lineflyer** [comment]
Changed the cleanup path for ```keys.xml``` on nightly, release, RC jobs. 
Running a new nightly build to check now.

**Comment by eddiemuc** [comment]
The different place of keys.xml was already noticed. Deletion is done in a job on CI and must be changed on server side. @bekuno volunteeres to do so. see #13761
