### ISSUE TITLE
RC release notification not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo-status#9]
I just ran a "Create release notification" on CI to get the RC from `RC-deployment` into `RC` but it is not working.

See:
http://ci.cgeo.org/view/Notifications/job/Create%20release%20notification/65/console

**Comment by Lineflyer** [comment]
Now I triggered again a notification for the new RC and it worked.
Seems to be caused by the fact, that a notification for all users was active at the first time trying.

**Comment by samueltardieu** [comment]
It should be completely uncorrelated.   It may be due to a transient communication problem. If you find a reproducer, I'll look at it when going back, otherwise I'll close it.

**Comment by Lineflyer** [comment]
Lets close for now. Will take a look for the next RCs.
